[package]
name = "merkle-distributor-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
merkle-distributor = { path = "../../programs/merkle-distributor" }
voter = { path = "../../programs/voter" }
shellexpand = "2.1.0"
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"
anchor-client = "0.28.0"
anyhow = "1.0.57"
solana-program = "1.16.12"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
spl-associated-token-account = "1.1.2"
spl-token = "3.5.0"
utils-cli = {path ="../utils"}